### ISSUE TITLE
Error at 'begin coverage matrix processing'

### ISSUE THREAD

**Issue by MadeleineCarruthers** [NUStatBioinfo/DegNorm#34]
Hi Frank,

So I did still end up with an error but much further on in the pipeline now. The following information is from a degNorm run performed on a subset of 6 samples. Samples are RNAseq data generated from lizard ovary tissue which was highly degraded. I used STAR for genome indexing (indexed with GTF file) and mapping. 

Now the GTF file reads in successfully and all reads for all 6 samples loaded successfully but I am getting an error right after the 'begin coverage matrix processing' part of the pipeline.

I have attached a copy of the log file, the traceback message from the command terminal.
[degnorm.log](https://github.com/NUStatBioinfo/DegNorm/files/3636776/degnorm.log)
[degNorm_traceback_error.txt](https://github.com/NUStatBioinfo/DegNorm/files/3636777/degNorm_traceback_error.txt)

And here is a Dropbox link to bam file for sample Lib-099, my GTF file and the script I am using to run the pipeline:  https://www.dropbox.com/s/62hpxck9t6202h2/Lib-099_sorted.bam?dl=0

Thanks very much in advance for your help.

All the best,

Madeleine

**Comment by ffineis** [comment]
Hi Madeleine,

I've attempted to fix this bug from the `hotfix/indexing` branch. Can you please install `degnorm` from there and attempt your run again?

Re-install commands:
```
git checkout hotfix/indexing
git pull origin hotfix/indexing
pip uninstall degnorm
rm -rf DegNorm.egg-info build dist
./install
```

And then run `degnorm` again.

If this does not work, please post two .bam files so I can test the pipeline end-to-end (as degnorm requires at a minimum 2 rna-seq files to run).

**Comment by MadeleineCarruthers** [comment]
Hi Frank,

Success!! Full pipeline has just finished without ant issues on a subset of the samples. All the results look how they should. 

Thank you so much for your time and help with this!

All the best,

Madeleine
