### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'str' and 'int' (DegNorm)

### ISSUE THREAD

**Issue by kohsh** [NUStatBioinfo/DegNorm#35]
Hey, 

I am currently running DegNorm (version 0.1.4) on SRA samples using gencode_v31_annotation.gtf file. 

I am facing error in DegNorm (11/12/2019 07:44:27) ---- Determining gene overlap structure across chromosomes, stag.

**Error_type:**
![Error_type](https://user-images.githubusercontent.com/46553150/68657066-176d8a00-0587-11ea-9c2c-eded5c9e05b7.png)

**GTF file format:**
![gencode_v31_gtf_format](https://user-images.githubusercontent.com/46553150/68656864-b6de4d00-0586-11ea-9321-7156ecc2e0b4.png)

Is this error correlated with GTF file? 

I would appreciate any help from your side.

Thanks,
Kosar

**Comment by ffineis** [comment]
Hello Kosar,

Thanks for using DegNorm, I will get back to you over the weekend.

**Comment by kohsh** [comment]
> Hello Kosar,
> 
> Thanks for using DegNorm, I will get back to you over the weekend.

Thanks .
Also, another question.
I've aligned fastqs against gencode annotation file using kallisto. As you may know, kallisto outputs are pseudo-bam-aligned. Am i going to face any problem running DegNorm on pseudo bam files?

**Comment by kohsh** [comment]
> > Hello Kosar,
> > Thanks for using DegNorm, I will get back to you over the weekend.
> 
> Thanks .
> Also, another question.
> I've aligned fastqs against gencode annotation file using kallisto. As you may know, kallisto outputs are pseudo-bam-aligned. Am i going to face any problem running DegNorm on pseudo bam files?

****** 
![Untitled](https://user-images.githubusercontent.com/46553150/69002453-c9b89f00-0943-11ea-8ed2-f9f715816f4d.png)
I've also aligned my fastq files using STAR, but still getting the same Error

**Comment by ffineis** [comment]
Kosar -

I am unfamiliar with kallisto and pseudo-bam files, but your issue is with the .gtf file. It appears as though the `start` field in the .gtf is coming in with string values in it. Can you please send over the .gtf?

Thanks,
Frank

**Comment by kohsh** [comment]
> Kosar -
> 
> I am unfamiliar with kallisto and pseudo-bam files, but your issue is with the .gtf file. It appears as though the `start` field in the .gtf is coming in with string values in it. Can you please send over the .gtf?
> 
> Thanks,
> Frank

Hey Frank,

thanks for your reply. Everything is working fine now.
