### ISSUE TITLE
DegNorm CLI runs dying

### ISSUE THREAD

**Issue by lquayle88** [NUStatBioinfo/DegNorm#44]
I have been trying to run DegNorm (v0.1.4) on 8 mRNA-Seq samples but the runs keep dying during the process of running NMF so I do not get the degradation-adjusted read counts out.

On my first run the last line written in the log file was after coverage/read count computations for all samples:

"NMF-OA iteration progress:   0%|          | 0/5 [00:00<?, ?it/s]"

The DegNorm command executed for this run was:

degnorm \
--bam-dir $degnorm_in \
-g $genome_dir/"$genome"_annotation.gtf \
-o $degnorm_out \
-p 12 \
--nmf-iter 50

I then used the warm start option in an attempt to "resume" the run using the following command:

degnorm \
--warm-start-dir $degnorm_out/degnorm_10042021_121650 \
-o $degnorm_out \
-p 12 \
--nmf-iter 50

and again the run died during the NMF computation; the log for this run was:

NMF-OA iteration progress:   0%|          | 0/5 [00:00<?, ?it/s]
NMF-OA iteration progress:  20%|██        | 1/5 [1:41:25<6:45:42, 6085.69s/it]
NMF-OA iteration progress:  40%|████      | 2/5 [3:21:44<5:02:18, 6046.10s/it]
NMF-OA iteration progress:  60%|██████    | 3/5 [5:01:49<3:20:54, 6027.32s/it]
NMF-OA iteration progress:  80%|████████  | 4/5 [6:42:28<1:40:32, 6032.20s/it]

I have checked that all of the requisite input files that I am using meet the requirements outlined on the Python package issues and bug reporting section of the contact page on the DegNeorm vignette (https://nustatbioinfo.github.io/DegNorm/about/contact/).

I am unsure if I doing something wrong/if so, what, and how to remedy this issue in order that the run can complete in order that I am able to access the degradation normalised read count matrix for downstream processing.

**Comment by ffineis** [comment]
Hey @lquayle88 thanks for reaching out. Can you please share what you mean by "runs keep dying?" Are you able to send the stacktrace of the error? I would also encourage you to check out the more recent R version of this package - http://www.bioconductor.org/packages/release/bioc/html/DegNorm.html
